services:
  devcontainer:
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: ..
    volumes:
      - ..:/workspaces/infrastructure:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
