name: wf-terraform-ci

env:
  CONFIGURATION: 'tests'
  ENVIRONMENT: 'dev'

on:
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  setup-env:
    runs-on: ubuntu-24.04
    outputs:
        configuration: ${{ steps.env.outputs.configuration }}
        environment: ${{ steps.env.outputs.environment }}
    steps:
      - name: Setup environment variables
        id: env
        run: |
          echo "configuration=$CONFIGURATION" >> "$GITHUB_OUTPUT"
          echo "environment=$ENVIRONMENT" >> "$GITHUB_OUTPUT"

  container-build-and-push:
    uses: armckinney/cicd/.github/workflows/rwf-container-build-and-push.yaml@main

  static-analysis:
    needs: [setup-env, container-build-and-push]
    uses: armckinney/cicd/.github/workflows/rwf-terraform-static-analysis.yaml@main
    with:
      container_image: ${{ needs.container-build-and-push.outputs.container_image }}
      configuration: ${{ needs.setup-env.outputs.configuration }}
      environment: ${{ needs.setup-env.outputs.environment }}
